name: image

on:
  push:
    branches: [ main ]

jobs:
  image_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2
    - name: Login to Quay
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2
      with:
        registry: quay.io/bradmccoydev1
        username: ${{ secrets.BOT_NAME }}
        password: ${{ secrets.BOT_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: quay.io/bradmccoydev1/test
          labels: latest
          file: build/Dockerfile